apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: hello
    context: .
    custom:
      buildCommand: docker build -f services/hello/Dockerfile -t hello .
      dependencies:
        dockerfile:
          path: services/hello/Dockerfile
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  helm:
    releases:
    - name: hello
      chartPath: helm/hello
      # valuesFiles:
      # - environment/local/hello/values.yaml
      # values:
      #   image: hello
      namespace: hello-local
